### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by XxKayNinexX** [kuroppoi/brainwine#23]
When I click on new player, then click register, it simply says: "Couldn't connect to the search service. Please try again in a bit."
Brainwine runs for about half a second and then quickly disappears. I am not able to run the Brainwine GUI. I have tried using the host.reg, but it does not work when I retry either.
I have Java 8, I have dragged the "Assembly-CSharp.dll" file into the Managed folder.
Please help me out, I really want to play this game again.

**Comment by kuroppoi** [comment]
Does anything of note happen when trying to run it? Are you using the latest version?

**Comment by XxKayNinexX** [comment]
Hi there, Brainwine is running now. But it is still saying "Couldn't connect to the search service. Please try again in a bit." whenever I register for a new deepworld account (I know you can't use your old account)

**Comment by XxKayNinexX** [comment]
Also yes, I am using the latest version.

**Comment by XxKayNinexX** [comment]
Do you know why this might be? Brainwine started running properly once I switched browsers. (Microsoft Edge to Google Chrome) and then I redownloaded the jar file and zip folder from chrome, that's when Brainwine started running without any issues. Now it is just the error message I get when creating a new user for Deepworld.

**Comment by kuroppoi** [comment]
Make sure that the server is actually running and that you start the game through the brainwine GUI

**Comment by XxKayNinexX** [comment]
I have been using the brainwine gui to start deepworld. Do you know how I can make sure the server is actually running? I put both gateway and api host on "local" but it's still not working.

**Comment by kuroppoi** [comment]
There is a “server” tab in the GUI.
Go there and press the “Start Server” button.

**Comment by XxKayNinexX** [comment]
I tried that, it says: "2023-05-01 08:19:17.276 ERROR - An unexpected exception occured
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.javalin.core.LoomUtil.getExecutorService(LoomUtil.kt:22) ~[brainwine.jar:?]
	at io.javalin.jetty.LoomThreadPool.<init>(JettyUtil.kt:90) ~[brainwine.jar:?]
	at io.javalin.jetty.JettyUtil.defaultThreadPool(JettyUtil.kt:28) ~[brainwine.jar:?]
	at io.javalin.jetty.JettyUtil.getOrDefault(JettyUtil.kt:20) ~[brainwine.jar:?]
	at io.javalin.jetty.JettyServer.server(JettyServer.kt:34) ~[brainwine.jar:?]
	at io.javalin.Javalin.start(Javalin.java:180) ~[brainwine.jar:?]
	at io.javalin.Javalin.start(Javalin.java:148) ~[brainwine.jar:?]
	at brainwine.api.GatewayService.<init>(GatewayService.java:41) ~[brainwine.jar:?]
	at brainwine.api.Api.<init>(Api.java:34) ~[brainwine.jar:?]
	at brainwine.ServerThread.run(ServerThread.java:32) ~[brainwine.jar:?]
Caused by: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
	at jdk.internal.misc.PreviewFeatures.ensureEnabled(PreviewFeatures.java:49) ~[?:?]
	at java.lang.Thread.ofVirtual(Thread.java:859) ~[?:?]
	at java.util.concurrent.Executors.newVirtualThreadPerTaskExecutor(Executors.java:274) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	... 11 more"

**Comment by kuroppoi** [comment]
Well that’s stupid. Try using an older Java version, like 17.

**Comment by XxKayNinexX** [comment]
ok thank you so much I will let you know if it works

**Comment by XxKayNinexX** [comment]
ok I tried using java 17 but it is just doing what i said it was doing at the beginning of this issue again. :/

**Comment by XxKayNinexX** [comment]
now brainwine won't run again

**Comment by XxKayNinexX** [comment]
when i try running brainwine, a small black rectangle pops up on my desktop for about half of a second or less, and there is no text that shows up or anything.

**Comment by XxKayNinexX** [comment]
is there anything I am doing wrong? does it matter that my laptop is an MSI?

**Comment by kuroppoi** [comment]
Hard to say. You could try to "run as" and then try every Java thing, if there are multiple.

**Comment by XxKayNinexX** [comment]
sorry for late reply but still not working.

**Comment by kuroppoi** [comment]
> sorry for late reply but still not working.

It might be worth to create a batch script or open a command prompt in the same directory as `brainwine.jar` and running 
`java -jar brainwine.jar` to see what might be going wrong.

**Comment by XxKayNinexX** [comment]
I wish I knew what that meant. Are you able to give me step by step instructions ?

**Comment by kuroppoi** [comment]
> I wish I knew what that meant. Are you able to give me step by step instructions ?

Open the folder where `brainwine.jar` is located
Click on the location bar (the wide bar right above the file list)
Clear all the text in it and type `cmd` and press enter
A command prompt (small black window) should appear
Type `java -jar brainwine.jar` in the command prompt and press enter
Tell me what happens, and any errors that occur

**Comment by XxKayNinexX** [comment]
> Open the folder where `brainwine.jar` is located Click on the location bar (the wide bar right above the file list) Clear all the text in it and type `cmd` and press enter A command prompt (small black window) should appear Type `java -jar brainwine.jar` in the command prompt and press enter Tell me what happens, and any errors that occur

Error: Unable to access jarfile brainwine.jar

C:\Users\caina\OneDrive\Desktop\brainwine>

**Comment by XxKayNinexX** [comment]
> > I tried that, it says: "2023-05-01 08:19:17.276 ERROR - An unexpected exception occured java.lang.reflect.InvocationTargetException: null at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] at io.javalin.core.LoomUtil.getExecutorService(LoomUtil.kt:22) ~[brainwine.jar:?] at io.javalin.jetty.LoomThreadPool.(JettyUtil.kt:90) ~[brainwine.jar:?] at io.javalin.jetty.JettyUtil.defaultThreadPool(JettyUtil.kt:28) ~[brainwine.jar:?] at io.javalin.jetty.JettyUtil.getOrDefault(JettyUtil.kt:20) ~[brainwine.jar:?] at io.javalin.jetty.JettyServer.server(JettyServer.kt:34) ~[brainwine.jar:?] at io.javalin.Javalin.start(Javalin.java:180) ~[brainwine.jar:?] at io.javalin.Javalin.start(Javalin.java:148) ~[brainwine.jar:?] at brainwine.api.GatewayService.(GatewayService.java:41) ~[brainwine.jar:?] at brainwine.api.Api.(Api.java:34) ~[brainwine.jar:?] at brainwine.ServerThread.run(ServerThread.java:32) ~[brainwine.jar:?] Caused by: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview at jdk.internal.misc.PreviewFeatures.ensureEnabled(PreviewFeatures.java:49) ~[?:?] at java.lang.Thread.ofVirtual(Thread.java:859) ~[?:?] at java.util.concurrent.Executors.newVirtualThreadPerTaskExecutor(Executors.java:274) ~[?:?] at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] ... 11 more"
> 
> The error you originally had should've been solved with the latest release. Try running it with the Java version you originally used: https://github.com/kuroppoi/brainwine/releases/latest

it keeps wanting me to "Open with" but I don't know what to select.

**Comment by kuroppoi** [comment]
> > > I tried that, it says: "2023-05-01 08:19:17.276 ERROR - An unexpected exception occured java.lang.reflect.InvocationTargetException: null at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] at io.javalin.core.LoomUtil.getExecutorService(LoomUtil.kt:22) ~[brainwine.jar:?] at io.javalin.jetty.LoomThreadPool.(JettyUtil.kt:90) ~[brainwine.jar:?] at io.javalin.jetty.JettyUtil.defaultThreadPool(JettyUtil.kt:28) ~[brainwine.jar:?] at io.javalin.jetty.JettyUtil.getOrDefault(JettyUtil.kt:20) ~[brainwine.jar:?] at io.javalin.jetty.JettyServer.server(JettyServer.kt:34) ~[brainwine.jar:?] at io.javalin.Javalin.start(Javalin.java:180) ~[brainwine.jar:?] at io.javalin.Javalin.start(Javalin.java:148) ~[brainwine.jar:?] at brainwine.api.GatewayService.(GatewayService.java:41) ~[brainwine.jar:?] at brainwine.api.Api.(Api.java:34) ~[brainwine.jar:?] at brainwine.ServerThread.run(ServerThread.java:32) ~[brainwine.jar:?] Caused by: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview at jdk.internal.misc.PreviewFeatures.ensureEnabled(PreviewFeatures.java:49) ~[?:?] at java.lang.Thread.ofVirtual(Thread.java:859) ~[?:?] at java.util.concurrent.Executors.newVirtualThreadPerTaskExecutor(Executors.java:274) ~[?:?] at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] ... 11 more"
> > 
> > 
> > The error you originally had should've been solved with the latest release. Try running it with the Java version you originally used: https://github.com/kuroppoi/brainwine/releases/latest
> 
> it keeps wanting me to "Open with" but I don't know what to select.

Java, OpenJDK, whichever you have.

**Comment by kuroppoi** [comment]
> > Open the folder where `brainwine.jar` is located Click on the location bar (the wide bar right above the file list) Clear all the text in it and type `cmd` and press enter A command prompt (small black window) should appear Type `java -jar brainwine.jar` in the command prompt and press enter Tell me what happens, and any errors that occur
> 
> Error: Unable to access jarfile brainwine.jar
> 
> C:\Users\caina\OneDrive\Desktop\brainwine>

This is strange. Are you sure that `brainwine.jar` is in there?
Maybe try completely re-installing Java. Doesn't have to be Java 8, Java 17 should work as well.

**Comment by kuroppoi** [comment]
Inactive
