### ISSUE TITLE
.app file won't launch and I don't know what a valid path is

### ISSUE THREAD

**Issue by CassOffGas** [kuroppoi/brainwine#38]
if someone could give me an example of a valid path to replace 'path/to/your/Deepworld.app' that would be amazing because right now I just don't know what to put, I'm a Mac user. Also, I'm assuming by shell you mean Terminal, but maybe not as I'm not completely sure.

**Comment by kuroppoi** [comment]
You can rename the app file to `Deepworld` and put it on your desktop.
That _should_ let you use `Desktop/Deepworld.app` as a path.

**Comment by CassOffGas** [comment]
Am I supposed to right click on the .app file and select New Terminal at Folder? When I type the command in there it says "No such file or directory Deepworld.app" even though I renamed the .app file to Deepworld and tried restarting my Mac

**Comment by CassOffGas** [comment]
<img width="1392" alt="Screenshot 2024-04-06 at 1 02 11 PM" src="https://github.com/kuroppoi/brainwine/assets/166205802/612651f1-4cb2-4e41-8993-215337389b33">
I figured out how to open Deepworld but now after I press play it gets frozen and shows red on brainwine. I took a screenshot so you can see what it says.

**Comment by kuroppoi** [comment]
Not quite enough information I'm afraid. Could you send the entire server log? Thanks!

**Comment by CassOffGas** [comment]
2024-04-06 14:40:59.979  WARN - NOTE: THIS SERVER IS INCOMPLETE! EXPECT BAD CODE, BUGS, AND MISSING FEATURES!
2024-04-06 14:40:59.981  INFO - Starting server ...
2024-04-06 14:40:59.981  INFO - Starting GameServer ...
2024-04-06 14:40:59.982  INFO - Registering commands ...
2024-04-06 14:40:59.984  INFO - Loading game configuration ...
2024-04-06 14:41:00.279  INFO - No config overrides found. To override game config properties, put them in a file called 'config_overrides.yml'
2024-04-06 14:41:00.280  INFO - Configuring ...
2024-04-06 14:41:00.441  INFO - Successfully loaded 1542 item(s)
2024-04-06 14:41:00.442  INFO - Caching versioned configurations ...
2024-04-06 14:41:00.615  INFO - Load complete! Took 631 milliseconds
2024-04-06 14:41:00.617  INFO - Loading achievements ...
2024-04-06 14:41:00.633  WARN - Some achievements could not be loaded due to missing implementations:
2024-04-06 14:41:00.634  WARN - [TradingAchievement, AgeAchievement, VotingAchievement, ArchitectAchievement, UndertakerAchievement, PositionAchievement, TrappingAchievement, InsurrectionAchievement, DeliveranceAchievement, KillerAchievement]
2024-04-06 14:41:00.634  INFO - Successfully loaded 54 achievements
2024-04-06 14:41:00.648  INFO - Successfully loaded 147 entities
2024-04-06 14:41:00.649  INFO - Loading entity spawns ...
2024-04-06 14:41:00.654  INFO - Loading loot tables ...
2024-04-06 14:41:00.662  INFO - Loading prefabs ...
2024-04-06 14:41:00.733  INFO - Successfully loaded 98 prefab(s)
2024-04-06 14:41:00.737  INFO - Loading zone generator configurations ...
2024-04-06 14:41:00.754  INFO - Starting async zone generator thread ...
2024-04-06 14:41:00.754  INFO - Loading zone data ...
2024-04-06 14:41:00.772  INFO - Successfully loaded 1 zone(s)
2024-04-06 14:41:00.772  INFO - Loading player data ...
2024-04-06 14:41:00.786  INFO - Successfully loaded 1 player(s)
2024-04-06 14:41:00.787  INFO - Registering requests ...
2024-04-06 14:41:00.807  INFO - Registering messages ...
2024-04-06 14:41:00.847  INFO - Using channel type class io.netty.channel.nio.NioEventLoopGroup
2024-04-06 14:41:00.847  INFO - Opening endpoint @ port 5002 ...
2024-04-06 14:41:00.898  INFO - All done! GameServer startup took 917 milliseconds
2024-04-06 14:41:00.898  INFO - Starting API ...
2024-04-06 14:41:00.899  INFO - Using data fetcher brainwine.DirectDataFetcher
2024-04-06 14:41:00.899  INFO - Loading configuration ...
2024-04-06 14:41:00.902  INFO - Starting GatewayService @ port 5001 ...
2024-04-06 14:41:01.013  INFO - Starting PortalService @ port 5003 ...
2024-04-06 14:41:01.016  INFO - All done! API startup took 118 milliseconds
2024-04-06 14:41:01.017  INFO - Server has started
2024-04-06 14:41:07.773  INFO - CassOffGas logged into zone Glumshed Dale from /127.0.0.1:49351
2024-04-06 14:41:08.278  WARN - java.io.IOException: Client sent invalid request: 55
2024-04-06 14:41:08.394 ERROR - Could not load chunk 820 of zone 5ce56157-d90f-b06a-a27c-85dbdfe7dcee
java.io.EOFException: null
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:498) ~[?:?]
	at java.io.RandomAccessFile.readUnsignedShort(RandomAccessFile.java:838) ~[?:?]
	at java.io.RandomAccessFile.readShort(RandomAccessFile.java:814) ~[?:?]
	at brainwine.gameserver.zone.ChunkManager.loadChunk(ChunkManager.java:169) ~[brainwine.jar:?]
	at brainwine.gameserver.zone.ChunkManager.getChunk(ChunkManager.java:241) ~[brainwine.jar:?]
	at brainwine.gameserver.zone.Zone.getChunk(Zone.java:1060) ~[brainwine.jar:?]
	at brainwine.gameserver.server.requests.BlocksRequest.process(BlocksRequest.java:49) ~[brainwine.jar:?]
	at brainwine.gameserver.server.PlayerRequest.process(PlayerRequest.java:20) ~[brainwine.jar:?]
	at brainwine.gameserver.server.pipeline.Connection.lambda$channelRead0$0(Connection.java:55) ~[brainwine.jar:?]
	at brainwine.gameserver.GameServer.tick(GameServer.java:83) ~[brainwine.jar:?]
	at brainwine.ServerThread.lambda$run$0(ServerThread.java:34) ~[brainwine.jar:?]
	at brainwine.gameserver.TickLoop.update(TickLoop.java:26) ~[brainwine.jar:?]
	at brainwine.ServerThread.run(ServerThread.java:42) ~[brainwine.jar:?]
2024-04-06 14:41:08.401 ERROR - An unexpected exception occured
java.lang.NullPointerException: Cannot invoke "brainwine.gameserver.zone.Chunk.getX()" because "chunk" is null
	at brainwine.gameserver.zone.Zone.onChunkLoaded(Zone.java:995) ~[brainwine.jar:?]
	at brainwine.gameserver.zone.ChunkManager.getChunk(ChunkManager.java:243) ~[brainwine.jar:?]
	at brainwine.gameserver.zone.Zone.getChunk(Zone.java:1060) ~[brainwine.jar:?]
	at brainwine.gameserver.server.requests.BlocksRequest.process(BlocksRequest.java:49) ~[brainwine.jar:?]
	at brainwine.gameserver.server.PlayerRequest.process(PlayerRequest.java:20) ~[brainwine.jar:?]
	at brainwine.gameserver.server.pipeline.Connection.lambda$channelRead0$0(Connection.java:55) ~[brainwine.jar:?]
	at brainwine.gameserver.GameServer.tick(GameServer.java:83) ~[brainwine.jar:?]
	at brainwine.ServerThread.lambda$run$0(ServerThread.java:34) ~[brainwine.jar:?]
	at brainwine.gameserver.TickLoop.update(TickLoop.java:26) ~[brainwine.jar:?]
	at brainwine.ServerThread.run(ServerThread.java:42) ~[brainwine.jar:?]
2024-04-06 14:41:08.405  INFO - Stopping server ...
2024-04-06 14:41:08.407  INFO - Shutting down GameServer ...
2024-04-06 14:41:08.408  INFO - Closing endpoints ...
2024-04-06 14:41:08.410  INFO - Stopping async zone generator thread ...
2024-04-06 14:41:08.759  INFO - Saving zone data ...
2024-04-06 14:41:08.762 ERROR - Zone save failure. id: 5ce56157-d90f-b06a-a27c-85dbdfe7dcee
java.lang.NullPointerException: Cannot invoke "brainwine.gameserver.zone.Chunk.isModified()" because "chunk" is null
	at brainwine.gameserver.zone.ChunkManager.saveChunks(ChunkManager.java:115) ~[brainwine.jar:?]
	at brainwine.gameserver.zone.Zone.saveChunks(Zone.java:1025) ~[brainwine.jar:?]
	at brainwine.gameserver.zone.ZoneManager.saveZone(ZoneManager.java:150) ~[brainwine.jar:?]
	at brainwine.gameserver.zone.ZoneManager.onShutdown(ZoneManager.java:78) ~[brainwine.jar:?]
	at brainwine.gameserver.GameServer.onShutdown(GameServer.java:118) ~[brainwine.jar:?]
	at brainwine.ServerThread.stopUnsafe(ServerThread.java:71) ~[brainwine.jar:?]
	at brainwine.ServerThread.run(ServerThread.java:47) ~[brainwine.jar:?]
2024-04-06 14:41:08.764  INFO - Saving player data ...
2024-04-06 14:41:08.793  INFO - Shutting down API ...
2024-04-06 14:41:08.806  INFO - Server has stopped

**Comment by kuroppoi** [comment]
The world you're trying to log into seems to be corrupt for some reason. Delete the `zones` folder, restart the server and try again.

**Comment by CassOffGas** [comment]
it seems to be working now. Thank you so much for your help! I really appreciate it.
